 Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [1]:
def func_generate_matrix(inputvector,n,increasing = False):
    if not increasing:
        output_matrix = np.array([i**(n-j-1) for i in inputvector for j in range(n)]).reshape(inputvector.size,n)
    else:
        output_matrix = np.array([i**j for i in inputvector for j in range(n)]).reshape(inputvector.size,n)
    return output_matrix

In [2]:
import numpy as np
input_vector = np.array([1,2,3,4,5])
output_matrix_len = 3
output_matrix_desc_order = func_generate_matrix(input_vector,output_matrix_len,False)
output_matrix_inc_order = func_generate_matrix(input_vector,output_matrix_len,True)
print("The length of the output matrix is : ",output_matrix_len, "\n")
print("The output of the matrix in the decreasing order of powers : \n ", output_matrix_desc_order, "\n")
print("The output of the matrix in the increasing order of powers : \n", output_matrix_inc_order, "\n")


The length of the output matrix is :  3 

The output of the matrix in the decreasing order of powers : 
  [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

The output of the matrix in the increasing order of powers : 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



 Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def calculate_mov_avg(inputarray,N):
    cumsum=[0]
    mov_avg = []
    for i,x in enumerate(inputarray,1):
        cumsum.append(cumsum[i-1]+x)
        if i>=N:
            movavg = round(((cumsum[i]-cumsum[i-N])/N),2)
            mov_avg.append(movavg)
    return mov_avg

In [5]:
input = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
calculate_mov_avg(input,3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]